### ISSUE TITLE
FluentHub UI suggestions

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#1]
**Repo page**
![image](https://user-images.githubusercontent.com/62196528/149245006-a7d65759-cb76-4cc0-bc08-42db469e564a.png)

**Comment by onein528** [comment]
Pinned items
![image](https://user-images.githubusercontent.com/62196528/150679878-67998bcf-fc9f-45ca-a843-eebf48d344e9.png)

**Comment by BobbyESP** [comment]
WOOOW, REPO PAGE IS INCREDIBLE

**Comment by BobbyESP** [comment]
> **Repo page** ![image](https://user-images.githubusercontent.com/62196528/149245006-a7d65759-cb76-4cc0-bc08-42db469e564a.png)

Add branch logo to the braches dropdown

**Comment by onein528** [comment]
Thanks :)
