### ISSUE TITLE
Adding Explore repositories and All Activity

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#12]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/60316747/150687213-800d2e1a-2b01-4513-8333-a4fe044a280c.png">

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/60316747/150687225-a08f75cc-d014-49ac-8340-f388f5b7ba22.png">

**Comment by onein528** [comment]
Let's discuss tomorrow.

(In fact, And I was thinking of making the Home page the default page like GitHub for mobile, and putting the profile, all activities, notifications, issues, PR, discussions, and settings of the signed-in users together on this page)
Previous screenshot in README.md:
![image](https://user-images.githubusercontent.com/62196528/149005711-1d48a379-f513-4c71-8e1c-794cbf4434c1.png)

**Comment by onein528** [comment]
However, I was afraid that including navigation that is not included in GitHub would complicate the navigation helper. Also, the reason for creating the Home page is the integration of all user page. However, the implementation of this is on top of my To-do.

**Comment by BobbyESP** [comment]
> Let's discuss another day.
> 
> (In fact, And I was thinking of making the Home page the default page like GitHub for mobile, and putting the profile, all activities, notifications, issues, PR, discussions, and settings of the signed-in users together on this page) Previous screenshot in README.md: ![image](https://user-images.githubusercontent.com/62196528/149005711-1d48a379-f513-4c71-8e1c-794cbf4434c1.png)

Oh yeah, this is a cool idea!

**Comment by BobbyESP** [comment]
> However, I was afraid that including navigation that is not included in GitHub would complicate the navigation helper. Also, the reason for creating the Home page is the integration of all user page. However, the implementation of this is on top of my To-do.

Oh , i understand.  If you want we can talk too this tomorrow

**Comment by BobbyESP** [comment]
I think it's becoming late to you.

**Comment by onein528** [comment]
I keep in mind. I'll create find page, activity(feed) page, and maybe explorer page(very row priority)
