### ISSUE TITLE
Accessing mostly protected memory areas and corrupting collections of repository

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#19]
**Describe the bug**
As title.

**To Reproduce**
1. Continue debugging until this exception occurs.
2. See an exception.

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows:
 - FluentHub:

**Additional context**

**Comment by onein528** [comment]
This problem no longer occurs. The next time we encounter this, reopen this issue.

**Comment by BobbyESP** [comment]
> This problem no longer occurs. The next time we encounter this, reopen this issue.

Ok, nice!
