### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#2]
Hi. I wanted to help in this project. I think it's an awesome idea and i'm a little bit experienced in UWP and C# and i hope this can be an opportunity for improving.

Hope you let me get into it. Thanks!

**Comment by onein528** [comment]
Thank you/

Yes, of course!! I invited you to this repo.

**Comment by onein528** [comment]
I will create organization for this and add you as its member!

**Comment by BobbyESP** [comment]
Oh! Thank you a lot!

**Comment by BobbyESP** [comment]
The invitation says to me that it's revoked

**Comment by onein528** [comment]
Fix it. add you to fluenthub-uwp organization member👍

**Comment by BobbyESP** [comment]
Thanks a lot! In a few hours i'm going to start to explore the code, now im at school

**Comment by onein528** [comment]
Actually, I don't know to develop multiple people.
There may be design conflicts, should I now create the "dev" branch and be approved in the PR before marging it?

**Comment by BobbyESP** [comment]
Yea, maybe it's a good idea. Developing in another branch, and when it's ready, merge it with the main one

**Comment by onein528** [comment]
Ok let's go!

**Comment by onein528** [comment]
> Thanks a lot! In a few hours i'm going to start to explore the code, now im at school

I'm teenager too. so good.
And member permission is okey? this is good?

**Comment by BobbyESP** [comment]
Ok, nice! I dont know if member permission is good. Later i talk to you, need to go sirry

**Comment by BobbyESP** [comment]
But yes, i can edit

**Comment by onein528** [comment]
Please keep in mind that there is a time difference between Spain and Japan(Spain+8h).

**Comment by BobbyESP** [comment]
Ok, no problem! I will add the Japanish clock to my phone so

**Comment by BobbyESP** [comment]
Good night by the way!

**Comment by BobbyESP** [comment]
Hi, i cant get into the link to get the credentials for the app as Repository member by [this link](https://github.com/organizations/fluenthub-uwp/settings/applications/)

**Comment by onein528** [comment]
https://github.com/fluenthub-uwp/FluentHub/settings/secrets/actions

 we may be use this. you can access this page(your access role is ‘Maintain’)?

**Comment by BobbyESP** [comment]
No, i cant. And ok, i'll use a non-member!

**Comment by BobbyESP** [comment]
At yours 00:00 i'm gonna try to change the AppCredentials system to JSON. I saw that you tried because you have the implementations of them in the code but unused.

**Comment by onein528** [comment]
I was worried about deleting the repository by mistake, so I set the authority to `Write`, but I found that only the repo creator can delete or transfer it, so I promoted your authority to Admin. Sorry.

**Comment by onein528** [comment]
> Sorry, I dont know very well about organization privileges. so please continue by a non-member way to get app id/secret.
https://github.com/fluenthub-uwp/FluentHub/settings/secrets/actions
 we may be use this. you can access this page(your access role is ‘Maintain’)?

Can you?

**Comment by onein528** [comment]
To prevent commit conflicts, you cannot push to `main` branch directly by protected branches settings.
So you have to create a branch such as `BobbyESP/JsonAppCredentials` to push directly.
If you want marge this, open a PR to marge. Approval of two people(me and you) is required.

**Comment by BobbyESP** [comment]
Ok, nice.

**Comment by BobbyESP** [comment]
> > Sorry, I dont know very well about organization privileges. so please continue by a non-member way to get app id/secret.
> > https://github.com/fluenthub-uwp/FluentHub/settings/secrets/actions
> > we may be use this. you can access this page(your access role is ‘Maintain’)?
> 
> Can you?

And no, i cant

**Comment by onein528** [comment]
I'm confused now........ why......

**Comment by BobbyESP** [comment]
Ah yes, now i can

**Comment by BobbyESP** [comment]
> I was worried about deleting the repository by mistake, so I set the authority to `Write`, but I found that only the repo creator can delete or transfer it, so I promoted your authority to `Admin`. Sorry.

Sorry, didnt readed this

**Comment by onein528** [comment]
I'll create private repo to use for app credentials container.

**Comment by BobbyESP** [comment]
Later i see, i cant now sorry

**Comment by BobbyESP** [comment]
I need to see that about the credentials, sorry for the late

**Comment by onein528** [comment]
Yes. See this org's private repo for credentials container.

**Comment by BobbyESP** [comment]
I have this 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/60316747/150677538-a16127e7-8a54-4d0e-8665-da3fecde7245.png">

**Comment by onein528** [comment]
It couldn't be used as my goal of use.
So please use private repo's credentials
https://github.com/fluenthub-uwp/github-api-credentials

**Comment by BobbyESP** [comment]
Okk, thanks a lot!

**Comment by onein528** [comment]
This conversation will be forwarded [here](https://github.com/fluenthub-uwp/FluentHub/discussions/5).

**Comment by onein528** [comment]
Can you set `watch` to `All activity`?

![image](https://user-images.githubusercontent.com/62196528/150682990-15faa925-01b7-462e-aa4b-4073a2378c1c.png)

**Comment by onein528** [comment]
When merging, select "squash and marge" as the merging method and merge.

**Comment by onein528** [comment]
You can open a PR for `progressRing` branch

**Comment by BobbyESP** [comment]
> Can you set `watch` to `All activity`?
> 
> ![image](https://user-images.githubusercontent.com/62196528/150682990-15faa925-01b7-462e-aa4b-4073a2378c1c.png)

Done

**Comment by BobbyESP** [comment]
> When merging, select "squash and marge" as the merging method and merge.

Ok!

**Comment by onein528** [comment]
@BobbyESP Would you like to delete the all of yours previous branchs?

**Comment by BobbyESP** [comment]
Yes please XD

**Comment by BobbyESP** [comment]
I had headaches before with them.

**Comment by BobbyESP** [comment]
Sorry if i'm not working too much. I have exams this weeks

**Comment by onein528** [comment]
It's good at all. at all.

**Good luck with the exam!!**

**Comment by BobbyESP** [comment]
Thanks!
