### ISSUE TITLE
Bad sizing of Pinned repositories cards in the Profile View

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#23]
**Describe the bug**
As the title. My conclusion is that: If the project has no description and the name is short, it will appear bad sized.

**To Reproduce**
1. Open the app.
2. Go to the profile view.
3. See the pinned repos.

**Expected behavior**
All the pinned repo cards with the same size.

**Screenshots (optional)**
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/60316747/151695227-aec8b1b4-0280-4354-88b1-837eae6da015.png">

**Version**
 - Windows: 11 21H2 22000.434
 - FluentHub: Development version (Untagged). #20 PR

**Additional context**
No

**Comment by onein528** [comment]
In fact, it doesn't wrap the repository description.
That's because I was afraid of this. For some reason, the heights cannot be aligned.

**Comment by onein528** [comment]
Besides, the height of the user's special README file cannot be flexible.
README webview block is need to set the maximum height to 400, and if it's less than that, deploy according to that height.

**Comment by onein528** [comment]
Opppppps. Fixed.

**Comment by onein528** [comment]
![image](https://user-images.githubusercontent.com/62196528/151696592-59c0cfec-1be1-4b2d-95d4-167e4cf7cabc.png)

**Comment by onein528** [comment]
Next commit will contain this fix.

**Comment by onein528** [comment]
It also includes the possibility of hiding the star button of this repository block, because the star button is not displayed for pin items.

**Comment by BobbyESP** [comment]
Nice work men!!!
