### ISSUE TITLE
Create link like button style and label control

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#26]
**Is your feature request related to a problem? Please describe.**

*None*

**Describe the solution you'd like**

Replace the link in the GitHub site with a button to update the style.
Create resource dictionary for this.

**Describe alternatives you've considered**

**Additional context**

**Screenshots (optional)**

Suggested place:

![image](https://user-images.githubusercontent.com/62196528/152004300-4f9c73eb-bce9-43e0-b848-588f064e0252.png)

**Comment by onein528** [comment]
May be use those:

https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml#L30-L32
![image](https://user-images.githubusercontent.com/62196528/152007322-65841364-99cd-4152-9915-dcf943484d39.png)

https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Hyperlink_themeresources.xaml#L7-L9
![image](https://user-images.githubusercontent.com/62196528/152007540-e0924013-6337-42b6-a717-9f535f7332fd.png)

**Comment by BobbyESP** [comment]
Ahh yes, i just realized that. In the Open with Visual Studio we need to do the same

**Comment by onein528** [comment]
And we also create label or status control.

![image](https://user-images.githubusercontent.com/62196528/152144915-7d5aed5d-c065-4f91-8f1e-088a91c68862.png)

![image](https://user-images.githubusercontent.com/62196528/152144939-39c06f05-76c9-4a2f-a730-3f62f0dc51f5.png)

![image](https://user-images.githubusercontent.com/62196528/152144965-84070751-db19-444f-b58e-3e43c7bfc2b9.png)

**Comment by BobbyESP** [comment]
Yes! But i actually like the fluent design to them. Don't know if you like it

**Comment by onein528** [comment]
Yes i think so. think about design of them. 👀

**Comment by BobbyESP** [comment]
The tickness can have the color of the labels (in like in github); and the interior, that color, changing the transparency and so, merging the fluent design with that layer of color

**Comment by onein528** [comment]
How about?

![image](https://user-images.githubusercontent.com/62196528/152316169-a00f25c3-c682-4500-a217-f4fa96fd8c1c.png)

**Comment by BobbyESP** [comment]
Yoo, like that, nice!

**Comment by onein528** [comment]
![image](https://user-images.githubusercontent.com/62196528/152344181-e16f733b-7af9-4587-9b2c-b9179c26600a.png)

**Comment by BobbyESP** [comment]
Nice!!

**Comment by BobbyESP** [comment]
maybe that blue and some of them

**Comment by onein528** [comment]
yes

**Comment by onein528** [comment]
> May be use either:
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml#L30-L32 ![image](https://user-images.githubusercontent.com/62196528/152007322-65841364-99cd-4152-9915-dcf943484d39.png)
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Hyperlink_themeresources.xaml#L7-L9 ![image](https://user-images.githubusercontent.com/62196528/152007540-e0924013-6337-42b6-a717-9f535f7332fd.png)

Second way(just mock-up in xaml):
How do you feel? we should use first way?

![image](https://user-images.githubusercontent.com/62196528/152560990-1125478d-3efc-4afc-8329-1c895d5ae4da.png)

**Comment by onein528** [comment]
![image](https://user-images.githubusercontent.com/62196528/152561789-83ed82bb-716a-4030-980b-4e88ee29a184.png)

**Comment by BobbyESP** [comment]
> That first way(I think this is good):
> 
> ![image](https://user-images.githubusercontent.com/62196528/152561789-83ed82bb-716a-4030-980b-4e88ee29a184.png)
> 
> In https://github.com/fluenthub-uwp/FluentHub/pull/35

This one better
