### ISSUE TITLE
Fix relative path in the html string

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#27]
**Describe the bug**

This issue exists to link to PR.

**To Reproduce**

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows:
 - FluentHub:

**Additional context**

**Comment by onein528** [comment]
This is terrible:

![image](https://user-images.githubusercontent.com/62196528/152197857-3d40f178-6fde-4ad3-8409-36fc2bc4303f.png)

**Comment by BobbyESP** [comment]
Ahh, i know what are you saying.
