### ISSUE TITLE
Repos with no description crashing the app

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#28]
**Describe the bug**
Same as the title

**To Reproduce**
1. Go to a repository that has no description-

**Expected behavior**
Open the repository having no description

**Screenshots (optional)**
Cna't, just this 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/60316747/152194853-43f7ccd6-2bd1-49dd-8268-cbd42de08564.png">

**Version**
 - Windows:
 - FluentHub:

**Additional context**
No

**Comment by BobbyESP** [comment]
Tried to do a fix, but it doesn't wok

**Comment by BobbyESP** [comment]
Nah, fixed. I'm just dumb

**Comment by onein528** [comment]
Thanks.

**Comment by onein528** [comment]
Close by #25

**Comment by BobbyESP** [comment]
Yes, i'm merging it now
