### ISSUE TITLE
Repository page ScrollViewer position

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#31]
**Describe the bug**
As the title

**To Reproduce**
1. Go to repository page
2. Scroll down

**Expected behavior**

I don't know where to make it scrollable.

**Screenshots (optional)**

**Version**
 - Windows: Win11 22523.rs_prerelease
 - FluentHub: unversioning

**Additional context**

**Comment by onein528** [comment]
first suggestion

![image](https://user-images.githubusercontent.com/62196528/152302398-8a3f4257-690d-4c39-832a-46afe3b8500a.png)

second:

![image](https://user-images.githubusercontent.com/62196528/152302429-2b15b4ce-4bfe-47b6-91ca-c1f03b505495.png)

third(*out dated*)
![image](https://user-images.githubusercontent.com/62196528/152302477-b6c9d07a-d150-421b-b94a-582784530af0.png)

**Comment by onein528** [comment]
I have now inserted a script that disables vertical scrolling in WebView.

```cs
```

**Comment by BobbyESP** [comment]
Ok, the idea is getting that down while scrolling? That's actually my idea

**Comment by onein528** [comment]
wherea would you like?

**Comment by onein528** [comment]
second idea is good?

**Comment by BobbyESP** [comment]
I thought in the first one, but if u like the second one, we can use it

**Comment by onein528** [comment]
YES. go with first one
