### ISSUE TITLE
When clicking a pinned repo block before it's completely loaded, the app crashes

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#43]
**Describe the bug**

**To Reproduce**
1. Go to your profile and click some pinned repo before it's loaded (name, description...)
2. Click on it
3. See the app crashing

**Expected behavior**
Open the repo page anyways.

**Screenshots (optional)**
https://user-images.githubusercontent.com/60316747/152652468-60dc54ae-c660-4ce9-9989-8b5c28c64733.mp4

and

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/60316747/152652477-6a442459-eabb-4fec-bc83-ce1b5f5e99b8.png">

**Version**
 - Windows: 11
 - FluentHub: Not yet versioned

**Additional context**
No

**Comment by onein528** [comment]
there's no tag of button?

FYI, button tag is assigned as repository id.

**Comment by BobbyESP** [comment]
> there's no tag of button? no way.
> 
> FYI, button tag is assigned as repository id.
> 
> OK I'll find the solution to this issue. this issue will be fixed by next PR.

Ok nice! And thx for that info!

**Comment by onein528** [comment]
it will be replaced by wrappers enter github rest api so that dont causes such exceptions with try-catch syntax.
