### ISSUE TITLE
Roadmap 1.0.00

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#60]
### New features

- Repository clone/branch button
- Repository overview
- Issue/PR details
- Update label control
- Issue comment reaction
- Repository summary card
- User summary card
- Issue/PR summary card

like this:

![image](https://user-images.githubusercontent.com/62196528/154943395-38dd8d4e-3d6c-4b14-8ec5-c571899d18dc.png)

![image](https://user-images.githubusercontent.com/62196528/154943455-28cc5693-2ce7-4171-9db7-0837b9248eed.png)

![image](https://user-images.githubusercontent.com/62196528/154943474-3002ee55-8329-4726-93e1-0fd20e631081.png)

### Bug fixes

- Related #56

**Comment by BobbyESP** [comment]
OK, i think i can do somethings today afternoon.
