### ISSUE TITLE
Issue/PR page scrollviewer position

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#65]
## 1. (I like)

![image](https://user-images.githubusercontent.com/62196528/154957024-d890b18b-08cd-4999-b7b9-f4fe298f582b.png)

## 2. (Current)

![image](https://user-images.githubusercontent.com/62196528/154957182-25cef511-aa5e-426b-97f5-d7177f572683.png)

## 3. (Hmmm)

![image](https://user-images.githubusercontent.com/62196528/154957219-a773b585-a1fb-4222-ba55-45b9a7657b6e.png)

**Comment by onein528** [comment]
which position do you like?

**Comment by onein528** [comment]
I like first one

**Comment by BobbyESP** [comment]
I like first one too

**Comment by onein528** [comment]
ok!!!

**Comment by BobbyESP** [comment]
Maybe align this? 
![imaxe](https://user-images.githubusercontent.com/60316747/154957660-46bd5262-7ac3-4813-b17b-f1f7ae997646.png)
I like how it is but maybe it's better to align it

**Comment by onein528** [comment]
Where do you want to align it?

**Comment by BobbyESP** [comment]
Align the text with the icon (not the icon with the text)

**Comment by BobbyESP** [comment]
I'm at school now and i cant code
