### ISSUE TITLE
Starred repos takes too long to load

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-uwp/FluentHub#66]
**Describe the bug**
Same as title

**To Reproduce**
1. Go to "Marked with stars/ Starred"
 
**Expected behavior**
Fast starred repos list loading

**Screenshots (optional)**
Nope

**Version**
 - Windows:
 - FluentHub:

**Additional context**
Maybe changing the quantity of requested repos with stars makes it load faster.

**Comment by onein528** [comment]
yea. I know. but it maybe because of using GraphQL.NET
maybe.

**Comment by BobbyESP** [comment]
yea, or getting the 100 first starred in one request. It's better 30 per
30, like GitHub

**Comment by onein528** [comment]
getting starred repos have ability to get the specified number of repos
