### ISSUE TITLE
FluentHub v0.7.1 test publishing to Microsoft Store

### ISSUE THREAD

**Issue by onein528** [fluenthub-uwp/FluentHub#69]
**Describe the bug**

* All `Passed` certicication kit

**To Reproduce**

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows: win11 stable version
 - FluentHub: v0.7.1(v0.7.5)

**Additional context**

**Comment by onein528** [comment]
should i use windows 11 stable version?

**Comment by BobbyESP** [comment]
> should i use windows 11 stable version? or we need to improve class security. must use try-catch and in ViewModel, not code behind.

Maybe. If you want we can use try catch

**Comment by onein528** [comment]
> <img alt="image" width="856" src="https://user-images.githubusercontent.com/60316747/155156574-ade89b69-2d32-4d7d-841a-2c36f99034ff.png">
> 
> You made somebreak points?

no. Perhaps a breakpoint was created at run time to protect the system.

**Comment by BobbyESP** [comment]
Ahh ok

**Comment by BobbyESP** [comment]
Can you give me the dump?

**Comment by BobbyESP** [comment]
I dont know if you can give permissions to some people to upload to the store the app. Or just make the test

**Comment by onein528** [comment]
> I dont know if you can give permissions to some people to upload to the store the app. Or just make that test

if i can, yes i do.

**Comment by onein528** [comment]
> Can you give me the dump?

ok. in discord.

**Comment by BobbyESP** [comment]
> > Can you give me the dump?
> 
> ok. in discord.

nice

**Comment by BobbyESP** [comment]
> > I dont know if you can give permissions to some people to upload to the store the app. Or just make that test
> 
> oopps. ok. i dont have azure AD account so i cannot manage users.

Ok, no problem!

**Comment by BobbyESP** [comment]
I think naybe it's your windows version, because your last test to see if it's approved, failed, when for me succeded

**Comment by onein528** [comment]
yea. what i think. so i am needed to downgrade windows 11 dev to stable....
I'll cannot recieve latest updates for windows11. very missing.....

**Comment by onein528** [comment]
ok. passed. then, we can publish to ms store.

**Comment by onein528** [comment]
![image](https://user-images.githubusercontent.com/62196528/155337755-a1218fb4-b957-4f57-8253-4be40690765c.png)

**Comment by BobbyESP** [comment]
OH YESS
